# Generated by Django 5.0.2 on 2024-04-19 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp', 'mp4', 'webm'], 'Not a common image or video format.')])),
            ],
        ),
    ]
