version: '3'
services:
 nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /app/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - /app/media/:/app/media/
    extra_hosts:
      - "host.docker.internal:host-gateway"

 redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"