name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@main

      - name: Deployment with SSH Action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            set -e

            echo -e "\n>>> Updating deploy folder"
            cd /root/deploy/
            rm -r django-deployment
            git clone -b video https://github.com/skipglide/django-deployment.git
            echo ${{ github.repository }}

            echo -e "\n>>> Stopping Gunicorn"
            cd /app/
            . env/bin/activate
            ./scripts/super.sh stop gunicorn

            echo -e "\n>>> Deleting old files"
            rm -rf /app/django-deployment /app/config /app/scripts /app/dockerfiles

            echo -e "\n>>> Copying new files"
            cp -r /root/deploy/django-deployment /app/
            mv /app/django-deployment/config /app/
            mv /app/django-deployment/scripts /app/
            mv /app/django-deployment/dockerfiles /app/
            mv /app/django-deployment/requirements.txt /app/

            echo -e "\n>>> Installing Python packages"
            pip install -r /app/requirements.txt

            echo -e "\n>>> Running Django migrations"
            /app/django-deployment/manage.py migrate

            echo -e "\n>>> Collecting static files"
            /app/django-deployment/manage.py collectstatic

            echo -e "\n>>> Re-reading Supervisord config"
            /app/scripts/super.sh reread
            /app/scripts/super.sh update

            echo -e "\n>>> Starting Gunicorn"
            /app/scripts/super.sh start gunicorn