name: docker

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@main

      - name: Deployment with SSH Action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            set -e

            echo -e "\n>>> Stopping docker containers"
            cd /app/dockerfiles
            docker container kill $(docker container ls -q)

            echo -e "\n>>> Redeploying docker containers"
            docker rm $(docker ps --filter status=exited -q)
            docker up compose -d